# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

# Antecipação com sucesso: HTTP 200 / BD
POST http://127.0.0.1:8000/emprestimos/antecipar-parcela
Content-Type: application/json
Accept: application/json

{
  "codigoSolicitante": 0,
  "numeroContrato": "50017",
  "listaCompetencias": ["202501"]
}

###

# Antecipação com erro: HTTP 412 / UC
POST http://127.0.0.1:8000/emprestimos/antecipar-parcela
Content-Type: application/json
Accept: application/json

{
  "codigoSolicitante": 0,
  "numeroContrato": "6420",
  "listaCompetencias": ["202501"]
}

###
